spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/cleanland_api
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
debug: true
